# docker-compose.yml
version: '3.9'
services:
  pharmaintel-api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DRUGBANK_API_KEY=${DRUGBANK_API_KEY}
    restart: unless-stopped
